#!/bin/sh

echo 'Creating single header implementation'
LOCAL_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
py "$LOCAL_DIR/../scripts/make_single_header_impl.py"

git add "single_header_impl"

if ! git diff --quiet --cached single_header_impl; then
    echo "Contents of single_header_impl changed. Please check whether these changes are correct."
    exit -1
fi
